export default {
  name: 'state',
  title: 'Stan',
  type: 'document',
  fields: [
    {
      title: 'Nazwa stanu',
      name: 'name',
      type: 'string',
      options: {
        list: [
          {title: 'Alabama', value: 'Alabama'},
          {title: 'Alaska', value: 'Alaska'},
          {title: 'Arizona', value: 'Arizona'},
          {title: 'Arkansas', value: 'Arkansas'},
          {title: 'Connecticut', value: 'Connecticut'},
          {title: 'Dakota Południowa', value: 'South Dakota'},
          {title: 'Dakota Północna', value: 'North Dakota'},
          {title: 'Delaware', value: 'Delaware'},
          {title: 'Floryda', value: 'Florida'},
          {title: 'Georgia', value: 'Georgia'},
          {title: 'Hawaje', value: 'Hawaii'},
          {title: 'Idaho', value: 'Idaho'},
          {title: 'Illinois', value: 'Illinois'},
          {title: 'Indiana', value: 'Indiana'},
          {title: 'Iowa', value: 'Iowa'},
          {title: 'Kalifornia', value: 'California'},
          {title: 'Kansas', value: 'Kansas'},
          {title: 'Karolina Południowa', value: 'South Carolina'},
          {title: 'Karolina Północna', value: 'North Carolina'},
          {title: 'Kentucky', value: 'Kentucky'},
          {title: 'Kolorado', value: 'Colorado'},
          {title: 'Luizjana', value: 'Louisiana'},
          {title: 'Maine', value: 'Maine'},
          {title: 'Maryland', value: 'Maryland'},
          {title: 'Massachusetts', value: 'Massachusetts'},
          {title: 'Michigan', value: 'Michigan'},
          {title: 'Minnesota', value: 'Minnesota'},
          {title: 'Missisipi', value: 'Missisipi'},
          {title: 'Missouri', value: 'Missouri'},
          {title: 'Montana', value: 'Montana'},
          {title: 'Nebraska', value: 'Nebraska'},
          {title: 'Nevada', value: 'Nevada'},
          {title: 'New Hampshire', value: 'New Hampshire'},
          {title: 'New Jersey', value: 'New Jersey'},
          {title: 'Nowy Jork', value: 'New York'},
          {title: 'Nowy Meksyk', value: 'New Mexico'},
          {title: 'Ohio', value: 'Ohio'},
          {title: 'Oklahoma', value: 'Oklahoma'},
          {title: 'Oregon', value: 'Oregon'},
          {title: 'Pensylwania', value: 'Pennsylvania'},
          {title: 'Rhode Island', value: 'Rhode Island'},
          {title: 'Teksas', value: 'Texas'},
          {title: 'Tennessee', value: 'Tennessee'},
          {title: 'Utah', value: 'Utah'},
          {title: 'Vermont', value: 'Vermont'},
          {title: 'Waszyngton', value: 'Washington'},
          {title: 'Wirginia', value: 'Virginia'},
          {title: 'Wirginia Zachodnia', value: 'West Virginia'},
          {title: 'Wisconsin', value: 'Wisconsin'},
          {title: 'Wyoming', value: 'Wyoming'},
          {title: 'Dystrykt Kolumbii', value: 'District of Columbia'},
          {title: 'Kanada', value: 'Canada'},
          {title: 'Meksyk', value: 'Mexico'},
        ],
      },
    },
  ],
}
