export default {
  name: 'state',
  title: 'Stan',
  type: 'document',
  fields: [
    {
      title: 'Nazwa stanu',
      name: 'name',
      type: 'string',
      options: {
        list: [
          {title: 'Alabama-US', value: 'Alabama'},
          {title: 'Alaska-US', value: 'Alaska'},
          {title: 'Arizona-US', value: 'Arizona'},
          {title: 'Arkansas-US', value: 'Arkansas'},
          {title: 'Connecticut-US', value: 'Connecticut'},
          {title: 'Dakota Południowa-US', value: 'Dakota Południowa'},
          {title: 'Dakota Północna-US', value: 'Dakota Północna'},
          {title: 'Delaware-US', value: 'Delaware'},
          {title: 'Floryda-US', value: 'Floryda'},
          {title: 'Georgia-US', value: 'Georgia'},
          {title: 'Hawaje-US', value: 'Hawaje'},
          {title: 'Idaho-US', value: 'Idaho'},
          {title: 'Illinois-US', value: 'Illinois'},
          {title: 'Indiana-US', value: 'Indiana'},
          {title: 'Iowa-US', value: 'Iowa'},
          {title: 'Kalifornia-US', value: 'Kalifornia'},
          {title: 'Kansas-US', value: 'Kansas'},
          {title: 'Karolina Południowa-US', value: 'Karolina Południowa'},
          {title: 'Karolina Północna-US', value: 'Karolina Północna'},
          {title: 'Kentucky-US', value: 'Kentucky'},
          {title: 'Kolorado-US', value: 'Kolorado'},
          {title: 'Luizjana-US', value: 'Luizjana'},
          {title: 'Maine-US', value: 'Maine'},
          {title: 'Maryland-US', value: 'Maryland'},
          {title: 'Massachusetts-US', value: 'Massachusetts'},
          {title: 'Michigan-US', value: 'Michigan'},
          {title: 'Minnesota-US', value: 'Minnesota'},
          {title: 'Missisipi-US', value: 'Missisipi'},
          {title: 'Missouri-US', value: 'Missouri'},
          {title: 'Montana-US', value: 'Montana'},
          {title: 'Nebraska-US', value: 'Nebraska'},
          {title: 'Nevada-US', value: 'Nevada'},
          {title: 'New Hampshire-US', value: 'New Hampshire'},
          {title: 'New Jersey-US', value: 'New Jersey'},
          {title: 'Nowy Jork-US', value: 'Nowy Jork'},
          {title: 'Nowy Meksyk-US', value: 'Nowy Meksyk'},
          {title: 'Ohio-US', value: 'Ohio'},
          {title: 'Oklahoma-US', value: 'Oklahoma'},
          {title: 'Oregon-US', value: 'Oregon'},
          {title: 'Pensylwania-US', value: 'Pensylwania'},
          {title: 'Rhode Island-US', value: 'Rhode Island'},
          {title: 'Teksas-US', value: 'Teksas'},
          {title: 'Tennessee-US', value: 'Tennessee'},
          {title: 'Utah-US', value: 'Utah'},
          {title: 'Vermont-US', value: 'Vermont'},
          {title: 'Waszyngton-US', value: 'Waszyngton'},
          {title: 'Wirginia-US', value: 'Wirginia'},
          {title: 'Wirginia Zachodnia-US', value: 'Wirginia Zachodnia'},
          {title: 'Wisconsin-US', value: 'Wisconsin'},
          {title: 'Wyoming-US', value: 'Wyoming'},
          {title: 'Dystrykt Kolumbii-US', value: 'Dystrykt Kolumbii'},
          {title: 'Kanada', value: 'Kanada'},
          {title: 'Meksyk', value: 'Meksyk'},
        ],
      },
    },
  ],
}
